### ISSUE TITLE
Unable to send on-chain payment

### ISSUE THREAD

**Issue by deafboy** [akumaigorodski/wallet#107]
Version: 2.2.17.81

After filling in the address and the amount, the send button was greyed out. I was able to move the fee slider, but the fee rate, as displayed, was not affected. I was unable to reproduce this issue again, however, I suspect that the wallet was waiting to fetch the current suggested fee.

I suggest not blocking the UI while the fee rate is being discovered, and allow sending the tx if the user specifies the fee manually.

**Comment by btcontract** [comment]
Fee fetching happens once in a few hours in a separate thread, it has no influence on UI. 
There won't be a manual input option since fee slider is just that already.

This is a buggy behavior of course but apparently it's not easily reproducible so keeping this open until more is discovered about this.
