### ISSUE TITLE
Balance gone? 

### ISSUE THREAD

**Issue by Axanderism** [akumaigorodski/wallet#155]
I used SBW for my Bitcoin balance a few years ago and even transported it across devices using my passphrase. 

I tried BLW with the passphrase too but it never showed my balance. Now SBW doesn't either. What has happened to my funds? Nobody else has access to my passphrase or my phone, so where is my balance? Was the app not secure in the first place?

**Comment by fiatjaf** [comment]
By passphrase do you mean the mnemonic word list with 12 words? I hope you do, because passphrases cannot hold Bitcoin by themselves, only these lists of 12 words. And they never leave your phone so they could not have been stolen.

If you have the list of words your funds may be using an old [derivation path](https://learnmeabitcoin.com/technical/derivation-paths). Go to `Settings > Manage chain wallets` and select all the unchecked options, see if your funds show up.

If that doesn't work you'll have to figure out the derivation path and use a different wallet that supports manually specifying derivation paths, https://www.sparrowwallet.com for example, with your same list of words.

**Comment by Axanderism** [comment]
> By passphrase do you mean the mnemonic word list with 12 words? I hope you do, because passphrases cannot hold Bitcoin by themselves, only these lists of 12 or 24 words. And they never leave your phone so they could not have been stolen.
> 
> If you have the list of words your funds may be using an old [derivation path](https://learnmeabitcoin.com/technical/derivation-paths). Go to `Settings > Manage chain wallets` and select all the unchecked options, that should make your funds show up.
> 
> If that doesn't work you'll have to figure out the derivation path and use a different wallet that supports manually specifying derivation paths, https://www.sparrowwallet.com for example, with your same list of words.

Thanks so much for the advice. Ticking the boxes showed my expected balance again which was a relief! 

I'm guessing that doing anything with the balance  (moving it elsewhere etc) will cost me, right? I can't see any statement of fees anywhere.

(Apologies if that's an obvious question - I've only ever held this balance and never done anything else with Bitcoin. I'm not even clear on how to convert it into fiat currency.)

**Comment by fiatjaf** [comment]
It will cost you, but not very much, If you select the smallest possible fee (1sat/b) that will cost you no more than $0.05 in dollar terms, and these fees are working fine today. I think SBW will display a box to select the fees whenever you try to send the funds to any address.
