### ISSUE TITLE
LN payments mostly fail

### ISSUE THREAD

**Issue by iljah** [akumaigorodski/wallet#158]
Using v2.4.27-95 from fdroid and opened a new 300k sat channel to tippin.me few hours ago, don't have other channels. Tried to send maybe 20 payments of different size to different nodes (bitrefill being one) and all payments above 2k sats failed. Success rate for 2k sat payments is about 50/50 and those seemed to succeed within few seconds. Otherwise wallet wallet keeps switching between "preparing" and "N part(s) in-flight" where N starts at 1 and sometimes eventually increased to 8 or more before decreasing again.

Additional info for one failed payment eventually writes local failure: no routes found. Before that I see bunch of temporarychannelfailures with route fees usually larger than 2k which I'm sending. Is route fee calculated by wallet based on total capacity instead of amount sent?..

Not sure if this is same problem as in https://github.com/btcontract/wallet/issues/152

**Comment by Darth-Coin** [comment]
Ok will try to help you out with this.

1. SBW is an abandoned project now.
2. It was forked by fiatjaf / NBD Team into ObiWan wallet https://github.com/nbd-wtf/obw and is strongly recommended to migrate your old SBW wallet into OBW.  [Here I wrote a full guide about new OBW wallet](https://darthcoin.substack.com/p/obw-open-bitcoin-wallet) and inside you will find instructions how to migrate your old SBW.
3. Try opening various LN channels not just one. OBW uses by default MPP. Having more paths available will increase the rate of success payment. Try opening with better nodes like ZFR, LNbig, Boltz etc. that are real routing nodes Tippin.me is not a very good routing node.
4. When you have a failed payment mostly is due to not well synced LN graph, outdated or in the process. So if you see on top right the icon of sync LN, just wait until is gone.
5. Try to NOT use Tor. Tor is unreliable for LN path payments, most of the time is failing.

I hope this will help you.

**Comment by iljah** [comment]
Thanks I'll check out obw. Don't think I was using tor and ln graph seemed to be synced.
