### ISSUE TITLE
importing HW, the tx list is incomplete and not in a chronological order

### ISSUE THREAD

**Issue by pony-montana** [akumaigorodski/wallet#179]
importing an hardware wallet with ~30 txs, the tx list is incomplete and not in a chronological order. In particular, after the last update, it only shows 5 pseudorandom txs in the list (they are not the 5 lastest txs, they seems randomly selected).

**Comment by akumaigorodski** [comment]
There's a UI bug which will be fixed in next release, which is that some outgoing txs are not persisted (with no effect on wallet balance, it is always accurate). 

But other than that I've decided to limit number of visible txs to 5, I personally don't see much value in having a longer list, the only txs I'm really interested in observing are those which are not confirmed yet. Also, if some tx is of interest it can always be found by txid or label using a search tool.

**Comment by pony-montana** [comment]
I dont know if this choiche is appropriate for the UX of that app. I imagine cases where the limit of 5 txs could be a problem: if someone makes or receive some payments in bitcoin on a day (like a little "street-merchant"), and at the night he want to rapidly check what payments he did/received during the day, I think a full txs list is something a "simple bitcoin wallet" would needs to show. If, for performance, a hard cap on txs is needed, I think would be better to set it the highest possible.

**Comment by akumaigorodski** [comment]
I've had an alternative idea which is to send the last tx only by default (+ unconfirmed ones) but then have an "expand" button to show them all. It's probably more appropriate indeed.

**Comment by pony-montana** [comment]
I like the idea!
